//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.12.03 at 02:28:53 PM CET 
//


package com.weather.report.soap;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="city" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="reportDate" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="averageTemperature" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *         &lt;element name="minTemperature" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *         &lt;element name="maxTemperature" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *         &lt;element name="summary" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "city",
    "reportDate",
    "averageTemperature",
    "minTemperature",
    "maxTemperature",
    "summary"
})
@XmlRootElement(name = "getWeatherReportResponse")
public class GetWeatherReportResponse {

    @XmlElement(required = true)
    protected String city;
    @XmlElement(required = true)
    protected String reportDate;
    protected double averageTemperature;
    protected double minTemperature;
    protected double maxTemperature;
    @XmlElement(required = true)
    protected String summary;

    /**
     * Gets the value of the city property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCity() {
        return city;
    }

    /**
     * Sets the value of the city property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCity(String value) {
        this.city = value;
    }

    /**
     * Gets the value of the reportDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReportDate() {
        return reportDate;
    }

    /**
     * Sets the value of the reportDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReportDate(String value) {
        this.reportDate = value;
    }

    /**
     * Gets the value of the averageTemperature property.
     * 
     */
    public double getAverageTemperature() {
        return averageTemperature;
    }

    /**
     * Sets the value of the averageTemperature property.
     * 
     */
    public void setAverageTemperature(double value) {
        this.averageTemperature = value;
    }

    /**
     * Gets the value of the minTemperature property.
     * 
     */
    public double getMinTemperature() {
        return minTemperature;
    }

    /**
     * Sets the value of the minTemperature property.
     * 
     */
    public void setMinTemperature(double value) {
        this.minTemperature = value;
    }

    /**
     * Gets the value of the maxTemperature property.
     * 
     */
    public double getMaxTemperature() {
        return maxTemperature;
    }

    /**
     * Sets the value of the maxTemperature property.
     * 
     */
    public void setMaxTemperature(double value) {
        this.maxTemperature = value;
    }

    /**
     * Gets the value of the summary property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSummary() {
        return summary;
    }

    /**
     * Sets the value of the summary property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSummary(String value) {
        this.summary = value;
    }

}
