//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.12.03 at 12:54:29 PM CET 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://weather.com/report", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.weather.report.soap;
